version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    hostname: backend
    working_dir: /opt/logdetective-website/backend/src
    command: "uvicorn api:app --host 0.0.0.0 --port 5020"
    stdin_open: true
    tty: true
    ports:
      - 5020:5020
    volumes:
      - .:/opt/logdetective-website:z
      - persistent:/persistent
    env_file:
      - "./files/env"
    environment:
      - ENV=devel
      - FEEDBACK_DIR=/persistent/results
      - PYTHONPATH=/opt/logdetective-website/backend
  # The frontend container is only a quality of life for development.
  # For production, we will simply compile the ClojureScript into JavaScript
  # and deploy it.
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    hostname: frontend
    working_dir: /opt/logdetective-website/frontend
    command: >
      bash -c "
        npm install &&
        npx shadow-cljs watch app
      "
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 9630:9630
      - 3333:3333
    volumes:
      - .:/opt/logdetective-website:z
    env_file:
      - "./files/env"
    environment:
      - ENV=devel

volumes:
  persistent:
